language: cpp

matrix:
    include:
        - os: osx
          osx_image: xcode11.1
        - os: linux
          dist: bionic
          compiler: clang
          env:
              - CC=clang-8 CXX=clang++-8
        - os: windows

before_install:
    - $TRAVIS_BUILD_DIR/.travis/before-install-$TRAVIS_OS_NAME.sh

before_script:
    - mkdir build && cd build
    - $TRAVIS_BUILD_DIR/.travis/before-script-$TRAVIS_OS_NAME.sh

script:
    - $TRAVIS_BUILD_DIR/.travis/script-$TRAVIS_OS_NAME.sh

before_deploy:
    - mkdir -p $HOME/binaries/swiftshader-ext
    - export TARBALL=$HOME/binaries/swiftshader-ext/swiftshader-ext-$TRAVIS_OS_NAME-$TRAVIS_COMMIT.tgz
    - export HASHFILE=$HOME/binaries/swiftshader-ext/swiftshader-ext-$TRAVIS_OS_NAME-$TRAVIS_COMMIT.sha256
    - cd $TRAVIS_BUILD_DIR/build/install-ext && tar czf $TARBALL *
    - |-
        cd $HOME/binaries/swiftshader-ext
        if [ $TRAVIS_OS_NAME = "windows" ]; then
            certutil -hashfile $TARBALL SHA256 | sed -n '2,2p;2q' > $HASHFILE
        else
            shasum -a 256 -b $TARBALL > $HASHFILE
        fi
    - cd $HOME/binaries/swiftshader-ext && $SHASUM > 
    - export S3_URL='http://scintillator-synth-coverage.s3-website-us-west-1.amazonaws.com/binaries/swiftshader-ext/'$TARBALL
    - export FWD_HTML='<html><head><meta http-equiv="refresh" content="0; url='$S3_URL'" /></head></html>'
    - echo $FWD_HTML > $HOME/binaries/swiftshader-ext/swiftshader-ext-$TRAVIS_OS_NAME-latest.html

deploy:
    - provider: s3
      access_key_id: $AWS_KEY
      secret_access_key: $AWS_SECRET
      bucket: scintillator-synth-coverage
      local-dir: $HOME/binaries
      upload-dir: binaries
      verbose: true
      edge: true
      cleanup: false
      acl: public_read
      on:
        branch: master

